apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume
  namespace: vote
spec:
  storageClassName: mongo-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
