apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: db-hpa
  namespace: vote
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mongo
  targetCPUUtilizationPercentage: 80
